# Generated by Django 3.1.8 on 2021-04-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210428_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
