# Generated by Django 3.1.8 on 2021-04-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_auto_20210429_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_id',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
