# Generated by Django 3.1.8 on 2021-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210515_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similar_article_ids',
            field=models.ManyToManyField(related_name='_article_similar_article_ids_+', to='app1.Article', verbose_name='similar articles'),
        ),
    ]
